on:
    pull_request:
        types: [opened, edited, reopened, synchronize]

jobs:
    format-code:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 14
            - name: Install
              run: npm ci
            - name: Run eslint on changed files
              uses: CriminalInjuriesCompensationAuthority/github-actions/format-code@main
              with:
                  config_path: ".eslintrc"
                  ignore_path: ".eslintignore"
